[project]
name = "rag-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { email = "DucKhoa.Nguyen@topicus.nl" }
]
requires-python = ">=3.14"
dependencies = [
    "langchain>=1.4.2",
    "langchain-anthropic>=1.7.4",
    "langchain-community>=0.4.2",
    "langchain-core>=1.6.5",
    "langchain-openai>=1.6.6",
    "langgraph>=1.2.12",
    "python-dotenv>=1.2.3",
]

[project.scripts]
rag-course = "rag_course:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
